### ISSUE TITLE
Cannot match against 'undefined' or 'null' - incorrect path separators on Windows

### ISSUE THREAD

**Issue by singular1ty94** [codebandits/react-app-rewire-svg-react-loader#1]
Node throws an error on line 14 of `index.js` while trying to destructure the `findIndexAndRules` function, as seen below:

![runerror](https://user-images.githubusercontent.com/7959594/34655844-c89913a2-f464-11e7-9d66-a43ec2bf75a0.PNG)

This strangely obscure error caught me up for a while, after I assumed it was my own code or something wrong with my node version. Eventually I compared the `index.js` against a very similar Rewired plugin, `react-app-rewire-less`, and discovered that the issue was likely to do with my path separation on Windows versus Linux.

Running the test suite confirms that the naive `.contains` function can't properly cope with windows environment using `\\` path separator instead of Linux `/`. 

![jesttestfail](https://user-images.githubusercontent.com/7959594/34655852-ea67ef8a-f464-11e7-955b-d1d51ed641ea.PNG)

I have created a [pull request](https://github.com/codebandits/react-app-rewire-svg-react-loader/pull/2) that properly uses `path.sep` and `path.resolve` to support Windows path separators.

**Comment by lnhrdt** [comment]
Resolved with @singular1ty94's PR in #2!
